JEIEvents.hideItems((e) => {
  const hiddenItems = [
    "taverntokens:copper_coin",
    "taverntokens:iron_coin",
    "taverntokens:gold_coin",
    "taverntokens:netherite_coin",
    // OP items
    "sophisticatedstorage:xp_pump_upgrade",
    "sophisticatedstorage:advanced_pump_upgrade",
    "sophisticatedstorage:pump_upgrade",
    // Silver unification
    "eidolon:silver_sword",
    "eidolon:silver_pickaxe",
    "eidolon:silver_axe",
    "eidolon:silver_shovel",
    "eidolon:silver_hoe",
    "eidolon:silver_boots",
    "eidolon:silver_leggings",
    "eidolon:silver_chestplate",
    "eidolon:silver_helmet",
    "eidolon:raw_silver",
    "eidolon:raw_silver_block",
    "eidolon:silver_nugget",
    "eidolon:silver_ingot",
    "eidolon:silver_ore",
    "eidolon:deep_silver_ore",
    "embers:silver_sword",
    "embers:silver_pickaxe",
    "embers:silver_axe",
    "embers:silver_shovel",
    "embers:silver_hoe",
    "embers:raw_silver",
    "embers:raw_silver_block",
    "embers:silver_nugget",
    "embers:silver_ingot",
    "embers:silver_ore",
    "embers:deepslate_silver_ore",
    // Lead unification
    "eidolon:raw_lead",
    "eidolon:raw_lead_block",
    "eidolon:lead_nugget",
    "eidolon:lead_ingot",
    "eidolon:lead_ore",
    "eidolon:deep_lead_ore",
    "embers:lead_sword",
    "embers:lead_pickaxe",
    "embers:lead_axe",
    "embers:lead_shovel",
    "embers:lead_hoe",
    "embers:raw_lead",
    "embers:raw_lead_block",
    "embers:lead_nugget",
    "embers:lead_ingot",
    "embers:lead_ore",
    "embers:deepslate_lead_ore",
    "rehooked:wood_chain",
    "rehooked:blaze_chain",
    "rehooked:ender_chain",
    // Crab
    "crabbersdelight:crab_legs",
    // Bedrolls
    "#upgrade_aquatic:bedrolls",
    // Modpack utils
    "itemfilters:damage",
    "itemfilters:block",
    "itemfilters:max_count",
    "itemfilters:strong_nbt",
    "ftbquests:task_screen_configurator",
    "ftbquests:stage_barrier",
    "ftbquests:detector",
    "ftbquests:loot_crate_opener",
    "ftbquests:screen_1",
    "ftbquests:screen_3",
    "ftbquests:screen_5",
    "ftbquests:screen_7",
    "ftbquests:barrier",
    "itemfilters:weak_nbt",
    "itemfilters:custom",
    "itemfilters:always_true",
    "itemfilters:always_false",
    "itemfilters:or",
    "itemfilters:id_regex",
    "itemfilters:mod",
    "itemfilters:tag",
    "itemfilters:xor",
    "itemfilters:not",
    "itemfilters:and",
    // Energy
    "littlelogistics:energy_locomotive",
    "littlelogistics:energy_tug",
    "littlelogistics:vessel_charger",
    // Translocators
    "translocators:diamond_nugget",
    "cb_microblock:microblock",
    // Compressed items
    "vinery:apple_bag",
    "candlelight:beetroot_crate",
    "candlelight:carrot_crate",
    "candlelight:potato_crate",
    // Conflicts
    "quark:blackstone_furnace",
    "quark:dirty_glass",
    "quark:dirty_glass_pane",
    "sushigocrafting:rice_seeds",
    "sushigocrafting:rice",
    "crabbersdelight:can",
    // Crystal seeds
    "embers:uranium_crystal_seed",
    "embers:dawnstone_crystal_seed",
    "embers:tin_crystal_seed",
    "embers:zinc_crystal_seed",
    "embers:uranium_crystal_seed",
    "embers:platinum_crystal_seed",
    "embers:aluminum_crystal_seed",
    "embers:nickel_crystal_seed",
    // Furniture dupes
    "candlelight:dark_oak_cabinet",
    "candlelight:spruce_cabinet",
    "candlelight:birch_cabinet",
    "candlelight:oak_cabinet",
    "candlelight:acacia_cabinet",
    "candlelight:jungle_cabinet",
    "candlelight:mangrove_cabinet",
    "candlelight:warped_cabinet",
    "candlelight:crimson_cabinet",
    "candlelight:cherry_cabinet",
    "candlelight:bamboo_cabinet",
    "candlelight:red_nether_bricks_stove",
    "candlelight:quartz_stove",
    "candlelight:end_stove",
    "candlelight:cobblestone_stove",
    "candlelight:sandstone_stove",
    "candlelight:mud_stove",
    "herbalbrews:stove",
    "candlelight:granite_stove",
    "candlelight:deepslate_stove",
    "candlelight:stone_bricks_stove",
    // misc
    "eidolon:terminus_mirror",
  ];
  const masteries = [
    "blacksmith",
    "cultivator",
    "fisher",
    "florist",
    "gourmand",
    "plunderer",
    "shady_wizard",
    "sifter",
    "trapper",
    "shipping",
    "eidolon",
    "irons_spells",
    "embers",
    "biomancy",
    "ars_nouveau",
  ];
  masteries.forEach((mastery) => {
    hiddenItems.push(`society:${mastery}_mastery_trophy`);
  });

  e.hide(hiddenItems);
});
